package ExceptionHandling;

import java.util.Scanner;

public class Main 
{
	public static void main(String[] args) 
	{
		int c = 0;
		
		try
		{
			//c = 4/0;
			Scanner user = new Scanner(System.in);
			String s = user.nextInt();
		}
		catch(ArithmeticException e)
		{
			System.out.println("you broke it");
		}
		catch(Exception e)
		{
			System.out.println("you really broke it");
		}
	}
}
